---
theme: jekyll-theme-minimal
title: Ngoc-Quan Ha-Phan
description: Researcher
logo: images/quan.jpg
---

# Ngoc-Quan Ha-Phan

Welcome to my personal research page. I am a researcher dedicated to advancing knowledge in my field. Below, you can find more information about my work, publications, and contact details.

![Ngoc-Quan Ha-Phan](images/quan.jpg)

## About Me

I am passionate about [your research field]. My work primarily focuses on [specific topics of interest]. I aim to contribute to the scientific community through innovative research and collaboration.

## Research

Here, you can highlight your main research projects, goals, and methodologies. You might include brief descriptions of your ongoing projects, key findings, and future directions.

## Publications

List your key publications here. You might format it as follows:

- **Title of Paper 1** (Year). Journal Name. [Link to Paper]
- **Title of Paper 2** (Year). Journal Name. [Link to Paper]
- **Title of Paper 3** (Year). Journal Name. [Link to Paper]

## Contact

Feel free to reach out to me via email at [your email address] or connect with me on [LinkedIn/Twitter/other social media platforms].

---

© 2024 Ngoc-Quan Ha-Phan. All rights reserved.
